import { PixelSpriteData } from '../types/pixel';
const t={'.':'transparent'};
export const mountain:PixelSpriteData={id:'mountain',width:48,height:24,palette:{...t,M:'#20334b',N:'#13263a',S:'#59606a'},pixels:Array.from({length:24},(_,y)=>Array.from({length:48},(_,x)=> y>Math.abs(x-13)+5?'M':y>Math.abs(x-33)+9?'N':(y===Math.abs(x-13)+6&&x<20?'S':'.')).join(''))};
export const pine:PixelSpriteData={id:'pine',width:12,height:20,palette:{...t,P:'#071b1d',Q:'#0d2825',T:'#2b1b12'},pixels:['.....P......','....PPP.....','...PPPPP....','....PQP.....','..PPPPPPP...','...PPQPP....','..PPPPPPP...','.PPPPQPPPP..','...PPPPP....','..PPPPPPP...','.PPPPPPPPP..','PPPPPQPPPPP.','....TTT.....','....TTT.....','....TTT.....','....TTT.....','............','............','............','............']};
export const house:PixelSpriteData={id:'house',width:44,height:34,palette:{...t,W:'#5b3a22',D:'#2b1b12',S:'#59606a',R:'#1b1210',G:'#c8963e',L:'#f0c36a'},pixels:Array.from({length:34},(_,y)=>Array.from({length:44},(_,x)=>{if(y<12&&Math.abs(x-22)<y+3)return y%3?'R':'D'; if(y>=12&&x>4&&x<40&&y<31)return (x%9===0||y%7===0)?'W':'S'; if((x>15&&x<22&&y>17&&y<26)||(x>30&&x<36&&y>16&&y<24))return (x+y)%2?'G':'L'; if(x>21&&x<28&&y>22)return 'D'; return '.'}).join(''))};
export const well:PixelSpriteData={id:'well',width:24,height:20,palette:{...t,S:'#59606a',D:'#2d343d',W:'#5b3a22',L:'#e7a64b'},pixels:['...WWWWWWWWWWWW...','..W..........W..','.W............W.','................','..SSSSSSSSSSSS..','.SDDSDDSDDSDDS.','.SSSSSSSSSSSSSS.','..SDDSDDSDDSDD..','..SSSSSSSSSSSS..','....D......D....','....D..LL..D....','....DDDDDDDD....','................','................','................','................','................','................','................','................']};
export const banner:PixelSpriteData={id:'banner',width:10,height:18,palette:{...t,B:'#1e4163',G:'#c8963e',R:'#8e3333'},pixels:['GGGGGGGGGG','GBBBBBBBBG','GBBBGGBBBG','GBBGGGGBBG','GBBBGGBBBG','GBBBBBBBBG','GBBBBBBBBG','GBBBBBBBBG','GBBBBBBBBG','GBBBBBBBBG','GBBBGGBBBG','GBBBBBBBBG','GBBBBBBBBG','.BBBBBB..','..BBBB...','...BB....','..........','..........']};
export const lantern:PixelSpriteData={id:'lantern',width:7,height:10,palette:{...t,W:'#5b3a22',L:'#f0c36a',O:'#e77f32'},pixels:['..W....','.WLW...','WLOLW..','.WLW...','..W....','..W....','.......','.......','.......','.......']};
export const guardPost:PixelSpriteData={id:'guard-post',width:18,height:18,palette:{...t,W:'#5b3a22',D:'#2b1b12',R:'#8e3333'},pixels:['..RRRRRRRRRR..','..RDDDDDDDDR..','...W......W...','...W......W...','...W......W...','...W......W...','...WWWWWWWW...','...W......W...','...W......W...','..............','..............','..............','..............','..............','..............','..............','..............','..............']};
